<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>Exe</OutputType>
		<ApplicationIcon>Resources\v2rayN.ico</ApplicationIcon>
	</PropertyGroup>

	<ItemGroup>
		<EmbeddedResource Include="Resources\v2rayN.ico">
			<CopyToOutputDirectory>Never</CopyToOutputDirectory>
		</EmbeddedResource>

		<EmbeddedResource Update="Resx\Resource.resx">
			<Generator>ResXFileCodeGenerator</Generator>
			<LastGenOutput>Resource.Designer.cs</LastGenOutput>
		</EmbeddedResource>

		<Compile Update="Resx\Resource.Designer.cs">
			<DesignTime>True</DesignTime>
			<AutoGen>True</AutoGen>
			<DependentUpon>Resource.resx</DependentUpon>
		</Compile>
	</ItemGroup>

</Project>
